### ISSUE TITLE
中文报错

### ISSUE THREAD

**Issue by liuweiccy** [qingliangcn/mslog#1]
![default](https://cloud.githubusercontent.com/assets/7008947/5835806/d6852f9a-a1a7-11e4-9993-d61d1e5392ea.png)
![default](https://cloud.githubusercontent.com/assets/7008947/5835811/e2f82b88-a1a7-11e4-8f14-6a1e1190d052.png)

**Comment by qingliangcn** [comment]
看样子使用了R17版本，R17的中文处理方式有所变化，应该这样使用：
?ERROR_MSG("~s", [<<"中文信息"/utf8>]).

不需要ts，字符串需要/utf8定义
