### ISSUE TITLE
跨天截断日志文件关键字错误

### ISSUE THREAD

**Issue by liuweiccy** [qingliangcn/mslog#2]
![1](https://cloud.githubusercontent.com/assets/7008947/5870991/9197b252-a311-11e4-9384-68df9aa9eb9f.png)
![default](https://cloud.githubusercontent.com/assets/7008947/5870992/999dcd38-a311-11e4-8ae4-304a182f0857.png)

**Comment by qingliangcn** [comment]
fixed in https://github.com/qingliangcn/mslog/commit/f028841b5832779d747442f091e103e849d646d8

**Comment by qingliangcn** [comment]
test passed, close this,thanks @liuweiccy
